In [1]:
import pandas as pd 
import numpy as np
import funciones as fs
import matplotlib.pyplot as plt
import seaborn as sns

EMPEZAMOS GENERANDO EL DF CON EL QUE TRABAJAREMOS

In [ ]:
df = pd.read_excel("data/european_cars.xlsx")

In [3]:
fs.chequeo_inicial(df)

Shape:
(6000, 25)
Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Model Name                 6000 non-null   object
 1   Brand                      6000 non-null   object
 2   Body Type                  6000 non-null   object
 3   Segment                    6000 non-null   object
 4   Usable Battery (kWh)       6000 non-null   float64
 5   Real Range (km)            6000 non-null   int64
 6   Efficiency (Wh/km)         6000 non-null   float64
 7   0–100 km/h (s)             6000 non-null   float64
 8   Top Speed (km/h)           6000 non-null   int64
 9   Towing Capacity (kg)       6000 non-null   int64
 10  Price (EUR)                6000 non-null   int64
 11  Charging Time (min)        6000 non-null   int64
 12  Max Charging Power (kW)    6000 non-null   int64
 13  Horsepower (HP)            6000 non-null   int64
 14  Torque (Nm)                6000 non-null   int64
 15  Maintenance Cost (€/year)  6000 non-null   int64
 16  Seating Capacity           6000 non-null   int64
 17  Boot Capacity (L)          6000 non-null   int64
 18  ADAS Level                 6000 non-null   object
 19  Safety Rating (Euro NCAP)  6000 non-null   int64
 20  Usage Type                 6000 non-null   object
 21  Energy Cost (€/100km)      6000 non-null   float64
 22  Insurance Rating           6000 non-null   int64
 23  Powertrain Type            6000 non-null   object
 24  Fuel Type                  6000 non-null   object
dtypes: float64(4), int64(13), object(8)
memory usage: 1.1+ MB
None
Missing values:
Model Name                   0
Brand                        0
Body Type                    0
Segment                      0
Usable Battery (kWh)         0
Real Range (km)              0
Efficiency (Wh/km)           0
0–100 km/h (s)               0
Top Speed (km/h)             0
Towing Capacity (kg)         0
Price (EUR)                  0
Charging Time (min)          0
Max Charging Power (kW)      0
Horsepower (HP)              0
Torque (Nm)                  0
Maintenance Cost (€/year)    0
Seating Capacity             0
Boot Capacity (L)            0
ADAS Level                   0
Safety Rating (Euro NCAP)    0
Usage Type                   0
Energy Cost (€/100km)        0
Insurance Rating             0
Powertrain Type              0
Fuel Type                    0
dtype: int64
Describe (numericas):
       Usable Battery (kWh)  Real Range (km)  Efficiency (Wh/km)  \
count           6000.000000      6000.000000         6000.000000
mean              13.061500       808.089333          456.385583
std               26.924798       224.696719          157.938065
min                0.000000       180.000000          130.000000
25%                0.000000       686.000000          376.000000
50%                0.000000       900.000000          483.000000
75%                2.000000       924.000000          569.000000
max              120.000000      1100.000000          700.000000

       0–100 km/h (s)  Top Speed (km/h)  Towing Capacity (kg)    Price (EUR)  \
count     6000.000000       6000.000000           6000.000000    6000.000000
mean         9.134667        222.032167           1088.717833   53338.365000
std          1.690241         27.730867            603.671779   27422.230316
min          3.000000        140.000000              0.000000   18331.000000
25%          8.400000        204.000000            672.000000   35803.500000
50%          9.400000        228.000000           1061.500000   45038.000000
75%         10.300000        250.000000           1563.250000   60366.750000
max         13.100000        250.000000           2500.000000  160000.000000

       Charging Time (min)  Max Charging Power (kW)  Horsepower (HP)  \
count          6000.000000              6000.000000      6000.000000
mean              3.333000                33.287333       212.507333
std              11.775691                82.200581       118.376080
min               0.000000                 0.000000        70.000000
25%               0.000000                 0.000000       136.000000
50%               0.000000                 0.000000       182.000000
75%               0.000000                 0.000000       246.000000
max              60.000000               349.000000       649.000000

       Torque (Nm)  Maintenance Cost (€/year)  Seating Capacity  \
count  6000.000000                6000.000000       6000.000000
mean    331.340000                 611.023167          5.193000
std     166.809384                 172.886855          1.178834
min     100.000000                 200.000000          2.000000
25%     217.000000                 500.000000          5.000000
50%     291.000000                 589.000000          5.000000
75%     398.000000                 694.000000          6.000000
max     899.000000                1199.000000          8.000000

       Boot Capacity (L)  Safety Rating (Euro NCAP)  Energy Cost (€/100km)  \
count        6000.000000                 6000.00000            6000.000000
mean          516.938000                    4.10150               8.353215
std           193.252439                    0.67548               2.651774
min             0.000000                    3.00000               3.000000
25%           400.000000                    4.00000               6.347500
50%           518.000000                    4.00000               8.160000
75%           655.000000                    5.00000              10.120000
max           994.000000                    5.00000              17.130000

       Insurance Rating
count       6000.000000
mean           4.284833
std            2.056715
min            1.000000
25%            3.000000
50%            4.000000
75%            5.000000
max           10.000000
Describe (categoricas):
                      Model Name   Brand Body Type Segment ADAS Level  \
count                       6000    6000      6000    6000       6000
unique                      4758      46        10      11          8
top     Jaguar I-PACE EV400 2024  Toyota       SUV       C          1
freq                          18     312      1163    1734       3176

       Usage Type Powertrain Type Fuel Type
count        6000            6000      6000
unique          6               4         5
top      Personal          Hybrid    Petrol
freq         3903            1668      1666

HABIENDO CHEQUEADO QUE EL DF NO TIENE VALORES NULOS Y LOS TIPO DE DATO SON CORRECTOS, ELIMINAREMOS LAS COLUMNAS QUE NO UTILIZAREMOS EN ESTE ANALISIS Y A SU VEZ RENOMBRAREMOS LAS COLUMNAS PARA FACILITAR EL TRABAJO.

In [4]:
df_master = fs.config_columns(df)

In [5]:
df_master.columns

Index(['model_name', 'brand', 'body_type', 'segment', 'price_eur',
       'maintenance_cost_year', 'seating_capacity', 'boot_capacity_l',
       'safety_rating', 'energy_cost_100km', 'powertrain_type', 'fuel_type'],
      dtype='object')

In [6]:
df_master["powertrain_type"].value_counts()

powertrain_type
Hybrid    1668
Petrol    1666
Diesel    1666
EV        1000
Name: count, dtype: int64

EN PRIMER LUGAR VAMOS A CREAR UNA NUEVA VARIABLE SUSTENTABLE QUE CONTENGA LOS COCHES QUE SU FUEL-TYPE SEA HIBRIDA O EV.

In [7]:
df_master = fs.coches_sustentables(df_master)
df_master

,model_name,brand,body_type,segment,price_eur,maintenance_cost_year,seating_capacity,boot_capacity_l,safety_rating,energy_cost_100km,powertrain_type,fuel_type,sustainable
0,Kia R7 Pro,Kia,Sedan,D,57524,562,5,422,4,13.89,Petrol,Petrol,0
1,Fiat T-Class,Fiat,Crossover,D,51816,466,7,537,3,10.17,Diesel,Diesel,0
2,Mini P8x,Mini,Wagon,B,36041,609,5,740,4,7.24,Hybrid,Petrol+Electric,1
3,Honda F3x,Honda,Hatchback,A,25625,499,5,341,3,8.92,Petrol,Petrol,0
4,BMW E8 Pro,BMW,Hatchback,C,40468,511,5,465,3,5.36,Hybrid,Petrol+Electric,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,Renault Twingo E-Tech 2022,Renault,Wagon,Premium,53223,974,5,223,3,6.10,EV,Electric,1
5996,MG MG5 2024,MG,Crossover,Mid-Range,37448,890,7,323,4,5.40,EV,Electric,1
5997,Toyota bZ4X 2025,Toyota,Coupe,Mid-Range,45190,1150,7,512,5,5.40,EV,Electric,1
5998,Mercedes-Benz EQE 500 2023,Mercedes-Benz,Crossover,Luxury,118856,818,4,676,5,6.80,EV,Electric,1
5999,Fiat 500e 2023,Fiat,Wagon,Economy,25292,736,5,575,4,6.10,EV,Electric,1

In [8]:
df_master['sustainable'].mean()

np.float64(0.44466666666666665)

POR OTRO LADO, VAMOS A CREAR UNA COLUMNA FILTRANDO AQUELLOS COCHES QUE CUMPLEN LAS CARACTERISTICAS GENERALES PARA SER "FAMILIAR"

In [9]:
df_master = fs.familiares(df_master)
df_master

,model_name,brand,body_type,segment,price_eur,maintenance_cost_year,seating_capacity,boot_capacity_l,safety_rating,energy_cost_100km,powertrain_type,fuel_type,sustainable,coche_familiar
0,Kia R7 Pro,Kia,Sedan,D,57524,562,5,422,4,13.89,Petrol,Petrol,0,0
1,Fiat T-Class,Fiat,Crossover,D,51816,466,7,537,3,10.17,Diesel,Diesel,0,1
2,Mini P8x,Mini,Wagon,B,36041,609,5,740,4,7.24,Hybrid,Petrol+Electric,1,1
3,Honda F3x,Honda,Hatchback,A,25625,499,5,341,3,8.92,Petrol,Petrol,0,0
4,BMW E8 Pro,BMW,Hatchback,C,40468,511,5,465,3,5.36,Hybrid,Petrol+Electric,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,Renault Twingo E-Tech 2022,Renault,Wagon,Premium,53223,974,5,223,3,6.10,EV,Electric,1,0
5996,MG MG5 2024,MG,Crossover,Mid-Range,37448,890,7,323,4,5.40,EV,Electric,1,0
5997,Toyota bZ4X 2025,Toyota,Coupe,Mid-Range,45190,1150,7,512,5,5.40,EV,Electric,1,0
5998,Mercedes-Benz EQE 500 2023,Mercedes-Benz,Crossover,Luxury,118856,818,4,676,5,6.80,EV,Electric,1,0
5999,Fiat 500e 2023,Fiat,Wagon,Economy,25292,736,5,575,4,6.10,EV,Electric,1,1

In [10]:
df_master["coche_familiar"].value_counts(normalize=True)

coche_familiar
0    0.572
1    0.428
Name: proportion, dtype: float64

EL 38% DE LOS COCHES QUE SE COMERCIALIZAN LOS PODEMOS CONSIDERAR "FAMILIAR"

In [11]:
df_master[df_master['coche_familiar']==1]['sustainable'].mean()

np.float64(0.3987538940809969)

EL 40% DE LOS COCHES FAMILIARES SON ELECTRICOS O HIBRIDOS (ETIQUETAS "0" O "ECO")

In [12]:
df_master = fs.familiares(df_master, min_boot_l=500)
df_master['coche_familiar'].mean()

np.float64(0.38)

POR ULTIMO CREAMOS UNA VARIABLE QUE ESTABLEZCA EL COSTO ANUAL DE MANTENIMIENTO DE CADA VEHICULO, ASUMIENDO COMO MEDIA DE KM RECORRIDOS POR AÑO 15000KM

In [13]:
df_master = fs.costes_anuales(df_master)
df_master

,model_name,brand,body_type,segment,price_eur,maintenance_cost_year,seating_capacity,boot_capacity_l,safety_rating,energy_cost_100km,powertrain_type,fuel_type,sustainable,coche_familiar,costo_energia_anual,costo_total_anual
0,Kia R7 Pro,Kia,Sedan,D,57524,562,5,422,4,13.89,Petrol,Petrol,0,0,2083.5,2645.5
1,Fiat T-Class,Fiat,Crossover,D,51816,466,7,537,3,10.17,Diesel,Diesel,0,1,1525.5,1991.5
2,Mini P8x,Mini,Wagon,B,36041,609,5,740,4,7.24,Hybrid,Petrol+Electric,1,1,1086.0,1695.0
3,Honda F3x,Honda,Hatchback,A,25625,499,5,341,3,8.92,Petrol,Petrol,0,0,1338.0,1837.0
4,BMW E8 Pro,BMW,Hatchback,C,40468,511,5,465,3,5.36,Hybrid,Petrol+Electric,1,0,804.0,1315.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,Renault Twingo E-Tech 2022,Renault,Wagon,Premium,53223,974,5,223,3,6.10,EV,Electric,1,0,915.0,1889.0
5996,MG MG5 2024,MG,Crossover,Mid-Range,37448,890,7,323,4,5.40,EV,Electric,1,0,810.0,1700.0
5997,Toyota bZ4X 2025,Toyota,Coupe,Mid-Range,45190,1150,7,512,5,5.40,EV,Electric,1,0,810.0,1960.0
5998,Mercedes-Benz EQE 500 2023,Mercedes-Benz,Crossover,Luxury,118856,818,4,676,5,6.80,EV,Electric,1,0,1020.0,1838.0
5999,Fiat 500e 2023,Fiat,Wagon,Economy,25292,736,5,575,4,6.10,EV,Electric,1,1,915.0,1651.0

In [14]:
df_master.columns

Index(['model_name', 'brand', 'body_type', 'segment', 'price_eur',
       'maintenance_cost_year', 'seating_capacity', 'boot_capacity_l',
       'safety_rating', 'energy_cost_100km', 'powertrain_type', 'fuel_type',
       'sustainable', 'coche_familiar', 'costo_energia_anual',
       'costo_total_anual'],
      dtype='object')

YA CON EL DF ARMADO CON LAS COLUMNAS QUE NECESITAREMOS POR LO QUE GENERAMOS EL NUEVO .CSV PARA PASAR A SEGUIR EL ANALISIS EN SQL.

In [15]:
df_master.to_csv("cars_final.csv", index=False)

PROCEDEMOS A CONECTARNOS A SQL.

In [16]:
import mysql.connector

In [17]:
import getpass 
password = getpass.getpass()

In [18]:
conn = mysql.connector.connect(host='localhost',
                        user='root',
                        passwd=password)

In [19]:
cursor = conn.cursor()

cursor

UNA VEZ CONECTADOS, CREAMOS EL DATABASE

In [20]:
cursor.execute("CREATE DATABASE IF NOT EXISTS final_project;")

In [21]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    passwd=password,
    database="final_project"
)
cursor = conn.cursor()

CREAMOS LA TABLA DENTRO DEL DATABASE

In [22]:
from sqlalchemy import create_engine

engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/final_project")

df_master.to_sql("cars", con=engine, if_exists="replace", index=False)

6000

CHEQUEAMOS QUE SE HAYA CREADO CORRECTAMENTE Y NO SE HAYAN ELIMINADO FILAS

In [23]:
pd.read_sql("SELECT COUNT(*) AS n FROM cars;", con=engine)

      n
0  6000

HABIENDO REALIZADO LAS QUERIES, PROCEDEMOS A GENERAR DOS NUEVAS COLUMNAS PARA QUE PODAMOS TRABAJAR EN TABLEAU: "COSTO TOTAL 5 AÑOS" y "PROP CT 5Y - INGRESO FAMILIAR"

In [25]:
df_master["cto_5y"] = df_master["price_eur"] + 5 * df_master["costo_total_anual"]

In [26]:
income_ref = 34716

df_master["prop_cto_ingreso"] = df_master["cto_5y"] / income_ref

In [29]:
df_master.columns

Index(['model_name', 'brand', 'body_type', 'segment', 'price_eur',
       'maintenance_cost_year', 'seating_capacity', 'boot_capacity_l',
       'safety_rating', 'energy_cost_100km', 'powertrain_type', 'fuel_type',
       'sustainable', 'coche_familiar', 'costo_energia_anual',
       'costo_total_anual', 'cto_5y', 'prop_cto_ingreso'],
      dtype='object')

UNA VEZ GENERADAS LAS DOS COLUMNAS, CREAMOS UN NUEVO .CSV y PROCEDEMOS A TRABAJAR EN TABLEAU

In [30]:
df_master.to_csv("cars_analysis_final.csv", index=False)